name: Deploy to Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      if: github.event_name == 'pull_request'
      run: |
        # Add commands to run your tests here, e.g.,
        python manage.py test

    - name: Set up Django environment variables
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      shell: bash

    - name: Collect static files
      run: |
        python manage.py collectstatic --no-input

    - name: Migrate database
      run: |
        python manage.py migrate

    - name: Restart server
      if: github.event_name == 'push'
      run: |
        # Add commands to restart your Django server here, e.g.,
        sudo systemctl restart gunicorn
