name: Deploy to Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        python manage.py collectstatic --no-input

    - name: Migrate database
      run: |
        python manage.py migrate

